# Generated by Django 5.0.6 on 2024-05-17 04:59

import core.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_alter_customuser_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='admin', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Required. Digits and + only, no longer then 20 symbols and shorter then 6 symbols.', max_length=20, validators=[core.validators.validators.validate_phone_number], verbose_name='Phone number'),
        ),
    ]
